### ISSUE TITLE
데이터 모델링

### ISSUE THREAD

**Issue by GuruneLee** [dev-entually/DevCalendar#19]
- [x] 데이터 모델링

Estimation: 1

**Comment by GuruneLee** [comment]
손그림만 완성. figma 로 정리해서 png 따놓기.



![Image](https://user-images.githubusercontent.com/60911416/198867228-5933bdab-b9b4-4f6f-ae67-c5a35344c9fe.png)

**Comment by okyungjin** [comment]
@GuruneLee 마지막 멘션
