### ISSUE TITLE
Sprint 관리 방법 정리하기

### ISSUE THREAD

**Issue by GuruneLee** [dev-entually/DevCalendar#4]
Github에서 Sprint 관리하는 방법을 정리해서 문서화 하자

**Comment by okyungjin** [comment]
@GuruneLee 님, Wiki에 [Sprint 관리 방법](https://github.com/dev-entually/DevCalendar/wiki/Sprint-%EA%B4%80%EB%A6%AC-%EB%B0%A9%EB%B2%95) 작성했으니 Approve 처리할까요?

**Comment by okyungjin** [comment]
[프로젝트 설정 - Sprint 관리 방법](https://github.com/dev-entually/DevCalendar/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B4%80%EB%A6%AC#sprint-%EA%B4%80%EB%A6%AC-%EA%B8%B0%EB%B3%B8-rule) 으로 문서 옮겨짐.
