### ISSUE TITLE
상호리뷰 방안 고안

### ISSUE THREAD

**Issue by GuruneLee** [dev-entually/DevCalendar#5]
프론트/백엔드 상호리뷰 방식에 대해 고민하고, 문서화 하기

**Comment by okyungjin** [comment]
- [ ] 회의록 내용을 [프로젝트 관리](https://github.com/dev-entually/DevCalendar/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B4%80%EB%A6%AC) 문서로 옮기기

**Comment by GuruneLee** [comment]
@okyungjin 님, 리뷰어의 역할에 대해 [프로젝트 관리](https://github.com/dev-entually/DevCalendar/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B4%80%EB%A6%AC/_edit#reviewer-%EC%9D%98-%EC%97%AD%ED%95%A0) 문서에 정리하였습니다.

확인 후 피드백 없으면 이슈 close 부탁드려요

**Comment by okyungjin** [comment]
@GuruneLee 님, n은 3으로 하는 것이 어떨까요?
