### ISSUE TITLE
이슈 번호와 branch name을 바인딩 할 수 있는지 조사

### ISSUE THREAD

**Issue by okyungjin** [dev-entually/DevCalendar#6]
# TODO
- [x] 이슈 번호와 branch name을 바인딩 할 수 있는지 조사한다.

**Comment by okyungjin** [comment]
- feat: A new feature
- fix: A bug fix
- docs: Changes to documentation
- style: Formatting, missing semi colons, etc; no code change
- refactor: Refactoring production code
- test: Adding tests, refactoring test; no production code change
- chore: Updating build tasks, package manager configs, etc; no production code change

출처: https://udacity.github.io/git-styleguide/

**Comment by okyungjin** [comment]
1. 브랜치를 생성할 때 이슈 번호와 목적을 포함시킨다.
a. `feat/{issue-number}-{feature-name}` <br> (예시 `feature/6-button-component`)
2. Git Hooks의 pre-commit 기능을 사용하여 커밋 메세지를 `feat: {작성한 커밋 메세지} #6` 으로 만든다.
3. 이슈 번호가 포함된 상태로 커밋하게 되면 이슈 스레드에서 추적이 가능하다.

@GuruneLee 님, 이 내용으로 Wiki 작성해도 되는지 확인 부탁드립니다.

**Comment by GuruneLee** [comment]
@okyungjin 님, 해당 내용 확인했습니다

질문이 있는데, **커밋이 이슈번호가 포함되면, 이슈 스레드에서 추적 가능하다** 라는 말이

**이슈번호를 담은 커밋이 업데이트 될 때 마다, 이슈 스레드에 로그가 쌓인다** 라는 의미인가요??

**Comment by okyungjin** [comment]
네 지금 대화 나누는 페이지가 "이슈 스레드"를 말하는데, added a commit ~ 라는 내용으로 히스토리가 쌓여요. [여기](https://www.lesstif.com/gitbook/github-push-pr-pull-request-issue-129008869.html) 마지막 사진 보시면 됩니다!
(저작권 때문에 사진은 못 가져옴)

**Comment by GuruneLee** [comment]
답변감사합니다.
wiki 에 추가하면 좋을것 같습니다.

close #6

**Comment by okyungjin** [comment]
#16 에서 Git Hook 작성
