### ISSUE TITLE
PR, Commit 메세지에 템플릿을 강제할 수 있는지 조사

### ISSUE THREAD

**Issue by okyungjin** [dev-entually/DevCalendar#7]
# TODO
- [x] 유효하지 않은 PR, Commit 메세지를 입력할 경우 작업을 진행하지 못하도록 할 수 있는지 조사
- [x] IDE에서 타이핑을 도와주는 방법이 있는지

**Comment by okyungjin** [comment]
두 기능 다 pre-commit을 사용하면 가능하다!

**Comment by okyungjin** [comment]
@GuruneLee 님, 가능 여부는 파악했는데 pre-commit 설정 필요한 항목은 취합해서 "pre-commit 설정" 이슈로 포함시키면 좋을 것 같아요.

이건 PRE_SPRINT에 속해 있어서 일단 Close 처리하면 좋을 것 같은데 확인 부탁드려요.

**Comment by GuruneLee** [comment]
@okyungjin 님, 내용 확인했습니다.
경진님이 직접 이슈 만들어주시면 좋을듯 합니다.

이 이슈는 close 하겠습니다.

**Comment by okyungjin** [comment]
#16 에서 Git Hook 작성
